// E-2 Treaty Countries — based on U.S. Department of State official list
// Source: https://travel.state.gov/content/travel/en/us-visas/employment/treaty-trader-investor-visa-e.html
export const E2_TREATY_COUNTRIES = new Set([
  "Albania",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Cameroon",
  "Canada",
  "Chile",
  "Colombia",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Grenada",
  "Honduras",
  "Hungary",
  "Indonesia",
  "Iran",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kosovo",
  "Kyrgyzstan",
  "Latvia",
  "Liberia",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Mexico",
  "Moldova",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Senegal",
  "Serbia",
  "Singapore",
  "Slovak Republic",
  "Slovenia",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Togo",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "United Kingdom",
  "Yugoslavia",
]);

// ISO country code to country name mapping for common nationalities
export const COUNTRY_CODE_TO_NAME: Record<string, string> = {
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  BE: "Belgium",
  BR: "Brazil",
  CA: "Canada",
  CL: "Chile",
  CO: "Colombia",
  HR: "Croatia",
  CZ: "Czech Republic",
  DK: "Denmark",
  EC: "Ecuador",
  EE: "Estonia",
  FI: "Finland",
  FR: "France",
  DE: "Germany",
  GR: "Greece",
  HU: "Hungary",
  IN: "India",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  LV: "Latvia",
  LT: "Lithuania",
  LU: "Luxembourg",
  MX: "Mexico",
  MA: "Morocco",
  NL: "Netherlands",
  NZ: "New Zealand",
  NO: "Norway",
  PK: "Pakistan",
  PA: "Panama",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RS: "Serbia",
  SG: "Singapore",
  SK: "Slovak Republic",
  SI: "Slovenia",
  KR: "South Korea",
  ES: "Spain",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  TH: "Thailand",
  TR: "Turkey",
  UA: "Ukraine",
  GB: "United Kingdom",
  UY: "Uruguay",
  VE: "Venezuela",
};

export function isE2TreatyCountry(country: string): boolean {
  return E2_TREATY_COUNTRIES.has(country);
}
